import Link from "next/link";
import PortfolioSlider from "@/components/PortfolioSlider";
import ReviewsSlider from "@/components/ReviewsSlider";
import { books, reviews, services } from "./homeData";

const journey = [["01", "Idea", "A conversation about the story you want to tell."], ["02", "Write", "Build your manuscript with a writer who understands the work."], ["03", "Refine", "Strengthen every page through editing and careful revision."], ["04", "Publish", "Prepare a book designed to meet the world."], ["05", "Reach readers", "Plan the next chapter with marketing support when you need it."]];

export function ServicesSection() { return <section className="section home-services" id="services"><div className="container"><div className="home-section-head"><div><p className="eyebrow">The full shelf</p><h2>Everything your book needs. Under one roof.</h2></div><p>Choose the support that meets you where you are, or bring your entire book journey together with one collaborative team.</p></div><div className="home-service-grid">{services.map((service) => <Link className="home-service-card reveal" href={service.href} key={service.href}><span className="home-service-card__icon"><svg><use href={`#${service.icon}`} /></svg></span><h3>{service.title}</h3><p>{service.description}</p><span className="home-service-card__link">Learn more <svg><use href="#i-arrow-right" /></svg></span></Link>)}</div></div></section>; }

export function JourneySection() { return <section className="section home-journey"><div className="container"><div className="home-journey__heading"><p className="eyebrow">A considered process</p><h2>Your book has a journey. We stay with the story.</h2></div><ol className="home-journey__path">{journey.map(([number, title, detail]) => <li className="reveal" key={number}><span>{number}</span><div><h3>{title}</h3><p>{detail}</p></div></li>)}</ol></div></section>; }

export function PortfolioSection() { return <section className="section home-portfolio" id="portfolio"><PortfolioSlider eyebrow="Selected work" items={books} title="Stories we’ve helped bring to life" /></section>; }

export function WhySection() {
  const points = [["One team, one conversation", "Your book can move from early idea to a finished launch with the same people alongside you."], ["Expertise where it matters", "Bring in the right creative support for writing, editing, design, publishing, or marketing."], ["A process you can see", "Clear stages and honest communication keep the work understandable from page one onward."], ["Your story stays yours", "Your voice, perspective, and authorship remain at the center of every decision."]];
  return <section className="section home-why"><div className="container home-why__grid"><div className="home-why__intro"><p className="eyebrow">Why Connect with Writer</p><h2>More than a service. A publishing partner.</h2><p>Books are made through many disciplines. We make it easier to bring those disciplines together around the work that only you can create.</p><Link className="btn btn--ghost-dark" href="/about-us">Meet our approach <svg><use href="#i-arrow-right" /></svg></Link></div><div className="home-why__list">{points.map(([title, detail], index) => <article className="reveal" key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{detail}</p></div></article>)}</div></div></section>;
}

export function GenresSection() { const genres = ["Fiction", "Romance", "Thriller", "Memoir", "Children’s", "Self-Help", "Business", "Sci-Fi"]; return <section className="section home-genres"><div className="container"><p className="eyebrow">Many kinds of stories</p><div className="home-genres__layout"><h2>There’s room on the shelf for your perspective.</h2><p>From personal histories to imaginative new worlds, our services are shaped around the book you want to make.</p></div><div className="home-genre-list">{genres.map((genre) => <span key={genre}>{genre}</span>)}</div></div></section>; }
export function TestimonialsSection() { return <section className="section home-testimonials"><ReviewsSlider eyebrow="Author stories" items={reviews} title="The experience behind the finished book" /></section>; }
export function FinalCta() { return <section className="section home-final"><div className="container"><div className="home-final__panel"><span aria-hidden="true" className="interactive-circle home-final__circle" /><div><p className="eyebrow">A good place to begin</p><h2>Let’s talk about the book you want to bring to life.</h2><p>Wherever you are in the process, we’ll help you find a thoughtful next step.</p></div><div className="home-final__actions"><Link className="btn btn--primary" href="/contact">Start your book <svg><use href="#i-arrow-right" /></svg></Link><Link className="home-text-link home-text-link--light" href="/contact">Contact our team <svg><use href="#i-arrow-right" /></svg></Link></div></div></div></section>; }
